### ISSUE TITLE
TS error using injected properties

### ISSUE THREAD

**Issue by maddysrc** [vintl-dev/vintl#78]
**Is your request related to a problem? Please describe.**
When trying to use the injected properties like `$t` in my template, TypeScript complains.

**Describe the solution you'd like**
Bundle a file with typings for the injected properties. Appears `typings/globals.d.ts` tries to do that, but it's not getting packaged.

**Describe alternatives you've considered**
Writing my own `.d.ts` file or only using `useVIntl()`.

**Additional context**
I'm using the Nuxt module as well, but I figured the main repo is the more appropriate place.

**Comment by brawaru** [comment]
[4.4.1](https://github.com/vintl-dev/vintl/releases/tag/v4.4.1) should resolve this issue. Nuxt module is updated with that version in [1.7.1](https://github.com/vintl-dev/nuxt/releases/tag/%40vintl%2Fnuxt%401.7.1). Please give it a try :)

**Comment by maddysrc** [comment]
Works great, thank you!
